name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip install buildozer

    - name: Build APK
      run: |
        buildozer init
        sed -i 's/requirements =.*/requirements = python3,pygame/' buildozer.spec
        buildozer -v android debug
